---
- hosts: localhost
  gather_facts: true
  roles:
    - role: system
      tags: system
    - role: git
      tags: git
    - role: alacritty
      tags: alacritty
    - role: keychain
      tags: keychain
    - role: lazygit
      tags: lazygit
    - role: fzf
      tags: fzf
    - role: tmux
      tags: tmux
    - role: terraform
      tags: terraform
    - role: terragrunt
      tags: terragrunt
    - role: neovim
      tags: neovim
    - role: sequel-ace
      tags: sequel-ace
    - role: awscli
      tags: awscli
    - role: aliyun-cli
      tags: aliyun-cli
    - role: go
      tags: go
    - role: circleci-cli
      tags: circleci-cli
