---
- name: Install AWS CLI
  community.general.homebrew:
    name: awscli
    state: latest
  become: False

- name: Install AWS CLI Session Manager plugin
  community.general.homebrew_cask:
    name: session-manager-plugin
    state: latest
  become: False
