---
- name: Create oh-my-zsh custom lib directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.oh-my-zsh/custom/lib"
    state: directory
    mode: 0700

- name: Fix slow paste
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/lib/misc.zsh"
    content: ""
    mode: 0600
    force: false
