---
- name: Clone Powerlevel10k theme
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
    force: yes
    repo: git@github.com:romkatv/powerlevel10k.git
    single_branch: yes
    update: yes
    version: master
