---
- name: Install
  community.general.homebrew:
    name: tmux
    state: latest
  become: false

- name: Install oh-my-tmux
  ansible.builtin.git:
    clone: true
    depth: 1
    dest: "{{ ansible_user_dir }}/.config/tmux/.tmux"
    force: false
    repo: https://github.com/gpakosz/.tmux.git
    single_branch: true
    update: true
    version: master

- name: Install plugin manager
  ansible.builtin.git:
    clone: true
    depth: 1
    dest: "{{ ansible_user_dir }}/.config/tmux/.tmux/plugins/tpm"
    force: true
    repo: git@github.com:tmux-plugins/tpm.git
    single_branch: true
    update: true
    version: master

- name: Link tmux.conf
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.config/tmux/.tmux/.tmux.conf"
    dest: "{{ ansible_user_dir }}/.config/tmux/tmux.conf"
    state: link

- name: Stow tmux.conf.local
  ansible.builtin.file:
    src: "{{ role_path }}/templates/tmux.conf.local"
    dest: "{{ ansible_user_dir }}/.config/tmux/tmux.conf.local"
    state: link
