---
- name: Clone packer (plugin manager)
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    force: yes
    repo: https://github.com/wbthomason/packer.nvim.git
    single_branch: yes
    update: yes
    version: master
