---
- name: Install
  community.general.homebrew:
    name: neovim
    state: latest
  become: false

- name: Install ripgrep (file search)
  community.general.homebrew:
    name: ripgrep
    state: latest
  become: false

- name: Clone AstroNvim
  ansible.builtin.git:
    clone: true
    depth: 1
    dest: "{{ ansible_user_dir }}/.config/nvim"
    force: false
    repo: git@github.com:AstroNvim/AstroNvim.git
    single_branch: true
    update: false
    version: nightly

- name: Stow neovim user files
  ansible.builtin.file:
    src: "{{ role_path }}/templates"
    dest: "{{ ansible_user_dir }}/.config/nvim/lua/user"
    state: link
    force: true
